LRUCache
NAME
LRUCache -
Template cache with an LRU removal policy.
SYNOPSIS
#include <lru_cache.h>
Public Types
typedef std::list< std::pair< Key, Data > > List
Main cache storage typedef.
typedef List::iterator List_Iter
Main cache iterator.
typedef List::const_iterator List_cIter
Main cache iterator (const).
typedef std::vector< Key > Key_List
List of keys.
typedef Key_List::iterator Key_List_Iter
Main cache iterator.
typedef Key_List::const_iterator Key_List_cIter
Main cache iterator (const).
typedef std::map< Key, List_Iter > Map
Index typedef.
typedef std::pair< Key, List_Iter > Pair
Pair of Map elements.
typedef Map::iterator Map_Iter
Index iterator.
typedef Map::const_iterator Map_cIter
Index iterator (const).
Public Member Functions
LRUCache (const unsigned long Size)
Creates a cache that holds at most Size worth of elements.
~LRUCache ()
Destructor - cleans up both index and storage.
const unsigned long size (void) const
Gets the current abstract size of the cache.
const unsigned long max_size (void) const
Gets the maximum sbstract size of the cache.
void clear (void)
Clears all storage and indices.
bool exists (const Key &key)
Checks for the existance of a key in the cache.
void remove (const Key &key)
Removes a key-data pair from the cache.
void touch (const Key &key)
Touches a key in the Cache and makes it the most recently used.
Data * fetch_ptr (const Key &key, bool touch=true)
Fetches a pointer to cache data.
Data fetch (const Key &key, bool touch_data=true)
Fetches a copy of cached data.
bool fetch (const Key &key, Data &data, bool touch_data=true)
Fetches a pointer to cache data.
void insert (const Key &key, const Data &data)
Inserts a key-data pair into the cache and removes entries if neccessary.
const Key_List get_all_keys (void)
Get a list of keys.
Detailed Description
template<class Key, class Data, class Sizefn = Countfn< Data >> class LRUCache< Key, Data, Sizefn >
Template cache with an LRU removal policy.
This template creats a simple collection of key-value pairs that grows until the size specified at construction is reached and then begins discard the Least Recently Used element on each insertion.
Examples:
lru_example.cpp.
Definition at line 73 of file lru_cache.h.
Constructor & Destructor Documentation
template<class Key , class Data , class Sizefn = Countfn< Data >> LRUCache< Key, Data, Sizefn >::LRUCache (const unsigned long Size) [inline]
Creates a cache that holds at most Size worth of elements. Parameters:
Size maximum size of cache
Definition at line 101 of file lru_cache.h.
                                                     :
                                _max_size( Size ),
                                _curr_size( 0 )
                                {}
Member Function Documentation
template<class Key , class Data , class Sizefn = Countfn< Data >> const unsigned long LRUCache< Key, Data, Sizefn >::size (void) const [inline]
Gets the current abstract size of the cache. Returns:
current size
Definition at line 112 of file lru_cache.h.
Referenced by DEFINE_TEST().
{ return _curr_size; }
template<class Key , class Data , class Sizefn = Countfn< Data >> const unsigned long LRUCache< Key, Data, Sizefn >::max_size (void) const [inline]
Gets the maximum sbstract size of the cache. Returns:
maximum size
Definition at line 117 of file lru_cache.h.
Referenced by DEFINE_TEST().
{ return _max_size; }
template<class Key , class Data , class Sizefn = Countfn< Data >> bool LRUCache< Key, Data, Sizefn >::exists (const Key & key) [inline]
Checks for the existance of a key in the cache. Parameters:
key to check for
Returns:
bool indicating whether or not the key was found.
Definition at line 131 of file lru_cache.h.
Referenced by DEFINE_TEST().
                                                     {
                        SCOPED_MUTEX;
#else
                inline bool exists( const Key &key ) const {
#endif
                        return _index.find( key ) != _index.end();
                }
template<class Key , class Data , class Sizefn = Countfn< Data >> void LRUCache< Key, Data, Sizefn >::remove (const Key & key) [inline]
Removes a key-data pair from the cache. Parameters:
key to be removed
Definition at line 142 of file lru_cache.h.
Referenced by DEFINE_TEST().
                                                     {
#ifdef _REENTRANT
                        SCOPED_MUTEX;
#endif
                        Map_Iter miter = _index.find( key );
                        if( miter == _index.end() ) return;
                        _remove( miter );
                }
template<class Key , class Data , class Sizefn = Countfn< Data >> void LRUCache< Key, Data, Sizefn >::touch (const Key & key) [inline]
Touches a key in the Cache and makes it the most recently used. Parameters:
key to be touched
Definition at line 154 of file lru_cache.h.
Referenced by DEFINE_TEST().
                                                    {
                        SCOPED_MUTEX;
                        _touch( key );
                }
template<class Key , class Data , class Sizefn = Countfn< Data >> Data* LRUCache< Key, Data, Sizefn >::fetch_ptr (const Key & key, bool touch = true) [inline]
Fetches a pointer to cache data. Parameters:
key to fetch data for
touch whether or not to touch the data
Returns:
pointer to data or NULL on error
Definition at line 164 of file lru_cache.h.
Referenced by DEFINE_TEST().
                                                                            {
                        SCOPED_MUTEX;
                        Map_Iter miter = _index.find( key );
                        if( miter == _index.end() ) return NULL;
                        _touch( key );
                        return &(miter->second->second);
                }
template<class Key , class Data , class Sizefn = Countfn< Data >> Data LRUCache< Key, Data, Sizefn >::fetch (const Key & key, bool touch_data = true) [inline]
Fetches a copy of cached data. Parameters:
key to fetch data for
touch_data whether or not to touch the data
Returns:
copy of the data or an empty Data object if not found
Definition at line 177 of file lru_cache.h.
Referenced by DEFINE_TEST(), and dump().
                                                                            {
                        SCOPED_MUTEX;
                        Map_Iter miter = _index.find( key );
                        if( miter == _index.end() )
                                return Data();
                        Data tmp = miter->second->second;
                        if( touch_data )
                                _touch( key );
                        return tmp;
                }
template<class Key , class Data , class Sizefn = Countfn< Data >> bool LRUCache< Key, Data, Sizefn >::fetch (const Key & key, Data & data, bool touch_data = true) [inline]
Fetches a pointer to cache data. Parameters:
key to fetch data for
data to fetch data into
touch_data whether or not to touch the data
Returns:
whether or not data was filled in
Definition at line 194 of file lru_cache.h.
                                                                                        {
                        SCOPED_MUTEX;
                        Map_Iter miter = _index.find( key );
                        if( miter == _index.end() ) return false;
                        if( touch_data )
                          _touch( key );
                        data = miter->second->second;
                        return true;
                }
template<class Key , class Data , class Sizefn = Countfn< Data >> void LRUCache< Key, Data, Sizefn >::insert (const Key & key, const Data & data) [inline]
Inserts a key-data pair into the cache and removes entries if neccessary. Parameters:
key object key for insertion
data object data for insertion
Note:
This function checks key existance and touches the key if it already exists.
Definition at line 209 of file lru_cache.h.
Referenced by DEFINE_TEST().
                                                                       {
                        SCOPED_MUTEX;
                        // Touch the key, if it exists, then replace the content.
                        Map_Iter miter = _touch( key );
                        if( miter != _index.end() )
                                _remove( miter );
                        // Ok, do the actual insert at the head of the list
                        _list.push_front( std::make_pair( key, data ) );
                        List_Iter liter = _list.begin();
                        // Store the index
                        _index.insert( std::make_pair( key, liter ) );
                        _curr_size += Sizefn()( data );
                        // Check to see if we need to remove an element due to exceeding max_size
                        while( _curr_size > _max_size ) {
                                // Remove the last element.
                                liter = _list.end();
                                --liter;
                                _remove( liter->first );
                        }
                }
template<class Key , class Data , class Sizefn = Countfn< Data >> const Key_List LRUCache< Key, Data, Sizefn >::get_all_keys (void) [inline]
Get a list of keys. Returns:
list of the current keys.
Definition at line 236 of file lru_cache.h.
Referenced by dump().
                                                           {
                        SCOPED_MUTEX;
                        Key_List ret;
                        for( List_cIter liter = _list.begin(); liter != _list.end(); liter++ )
                                ret.push_back( liter->first );
                        return ret;
                }
Author
Generated automatically by Doxygen for C++ LRU Cache Template from the source code.