.TH "test" 3 "Sun May 15 2011" "Version 1.3" "C++ LRU Cache Template" \" -*- nroff -*-
.ad l
.nh
.SH NAME
test \- .TH "test" 3 "Sun May 15 2011" "Version 1.3" "C++ LRU Cache Template" \" -*- nroff -*-
.ad l
.nh
.SH NAME
test \-  
.IP "\fBMember \fBDEFINE_TEST\fP(lru_cache_1cycle) \fP" 1c
Basic creation and desctruction test 
.PP
.PP
 
.IP "\fBMember \fBDEFINE_TEST\fP(lru_cache_threads) \fP" 1c
Check for badness with multithreaded access, this is more of a stress test than an empirical test. 
.PP
.PP
 
.IP "\fBMember \fBDEFINE_TEST\fP(lru_cache_scope_check) \fP" 1c
Check that objects inserted in a different scope are still there. 
.PP
.PP
 
.IP "\fBMember \fBDEFINE_TEST\fP(lru_cache_stress) \fP" 1c
Insert lots of objects and benchmark the rate. 
.PP

